### ISSUE TITLE
Install DoSOCSv2 on ec2

### ISSUE THREAD

**Issue by ccarterlandis** [computationalmystic/augur-group13#1]
We need DoSOCSv2 installed on our ec2 instance. To provide DoSOCSv2 "as a service", we're wrapping it in a REST API built with Flask which will depend on DoSOCSv2 being installed on the server on which the API is running. In our case, this is an AWS ec2 instance. We've already had some troubles getting DoSOCSv2 installed, so this issue will serve as a central point of discussion for those troubles.

**Comment by PaulDGillis** [comment]
Dosocs2 is written in python 2 and thus right now needs to be installed via pip2. Right now Luke and I have been doing some testing and find it can crash depending on the project. I'm currently looking into the issue but may try forking dosocs2 and converting it to python 3.

**Comment by ccarterlandis** [comment]
There actually is a version of DoSOCSv2 [here](https://github.com/nebrethar/dosocsv2) that's already been converted to Python 3 😄

**Comment by ccarterlandis** [comment]
DoSOCSv2 has been almost completely successfully installed on a fresh ec2 instance. Only one issue remains at this time, the traceback for which can be seen here:
```
root@<hostname>:~ ∫ dosocs2 oneshot WorkshopExample/
dosocs2: WorkshopExample/: package_id: 1
dosocs2: running nomos on package 1
FATAL libfossscheduler.c.251: unable to open VERSION configuration: unable to open configuration file "/usr/local/etc/fossology/mods-enabled/nomossa/VERSION"
Traceback (most recent call last):
  File "/usr/local/bin/dosocs2", line 9, in <module>
    load_entry_point('dosocs2', 'console_scripts', 'dosocs2')()
  File "/root/dosocsv2/dosocs2/dosocs2.py", line 336, in main
    package = do_scan(**kwargs)
  File "/root/dosocsv2/dosocs2/dosocs2.py", line 143, in do_scan
    scanner.run(**scanner_kwargs)
  File "/root/dosocsv2/dosocs2/scannerbase.py", line 131, in run
    processed_files[file] = self.process_file(file)
  File "/root/dosocsv2/dosocs2/scanners/nomos.py", line 54, in process_file
    output = subprocess.check_output(args)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('/usr/local/share/fossology/nomos/agent/nomossa', '-S', 'WorkshopExample/.codacy.yml')' returned non-zero exit status 254
```

As evident above, the problem seems to be that nomos is unable to open the config file located at `/usr/local/etc/fossology/mods-enabled/nomossa/VERSION`. I'm not sure if this file is supposed to be user-created or not, and I have not been able to find references to this issue elsewhere in the DoSOCSv2 or FOSSology documentation.

**Comment by ccarterlandis** [comment]
I was able to fix this ^ issue by simply renaming `/usr/local/etc/fossology/mods-enabled/nomos/` to `/usr/local/etc/fossology/mods-enabled/nomossa/`. Closed.
