### ISSUE TITLE
Configure DoSOCSv2 to utilize PostgreSQL

### ISSUE THREAD

**Issue by ccarterlandis** [computationalmystic/augur-group13#6]
Due to its high performance on joins, we have elected to implement DoSOCSv2 in PostgresSQL. We have a schema created [here](https://github.com/computationalmystic/augur-group13/blob/master/sprint2/dosocs.sql), but we will need to make sure that the DB persists outside the program's memory so that it can be queried at any time.

DoSOCSv2 also has steps already for working with PostgreSQL, and although I have not reviewed these fully, I expect that we'll need to do more than just those instructions.

**Comment by Luke-Fisher** [comment]
For the sake of convenience here's the link to the [PostgreSQL DoSOCSv2 documentation](https://github.com/Nebrethar/DoSOCSv2#step-3-optional---add-postgresql-configuration). Hopefully it won't be as bad as we think it's going to be.

**Comment by ccarterlandis** [comment]
Following the DoSOCSv2 instructions was sufficient enough to get things up and running. I did run into a permissions error on the account I had created myself, but once I switched back to the one DoSOCSv2 automatically creates I had no problems. I opted to do this since I can't see any real benefit from having a separate user: the given one is perfectly sufficient.
